name: esp_monitor
description: ESP8266 Multi-Device Monitor
publish_to: 'none'
version: 1.2.0+3

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.1.0
  flutter_local_notifications: ^17.0.0
  shared_preferences: ^2.5.0
  audioplayers: ^6.1.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "#14141C"
  adaptive_icon_foreground: "assets/icon/app_icon_fg.png"
